### PR TITLE
[Consul] Add recovery for Consul Watcher (#764) and configure log level for not found KV (#765)

### LINKED ISSUE #764: Once Consul Watch fails it never recovers
### Expected Behavior

It should be able to recover or at least retry after a network failure

### Actual Behaviour

When network connection to Consul is lost a HttpClientResponseException is thrown and the Watcher stops working. Then, when the connections is back to normal the Watcher is already dead

`2025-10-02T11:15:30,607+02:00 ERROR 28128 --- [ntLoopGroup-3-4] i.m.d.c.w.AbstractWatcher:  Watching kvPath=config/micronaut/service failed
io.micronaut.http.client.exceptions.HttpClientResponseException: rpc error making call: EOF
	at io.micronaut.http.client.netty.DefaultHttpClient.makeErrorFromRequestBody(DefaultHttpClient.java:2129) ~[micronaut-http-client-4.8.11.jar:4.8.11]
	at io.micronaut.http.client.netty.DefaultHttpClient.handleExchangeResponse(DefaultHttpClient.java:952) ~[micronaut-http-client-4.8.11.jar:4.8.11]
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$exchange$8(DefaultHttpClient.java:905) ~[micronaut-http-client-4.8.11.jar:4.8.11]
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72) ~[micronaut-core-4.8.11.jar:4.8.11]
	at io.micronaut.core.execution.DelayedExecutionFlowImpl$FlatMap.apply(DelayedExecutionFlowImpl.java:332) ~[micronaut-core-4.8.11.jar:4.8.11]
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.work(DelayedExecutionFlowImpl.java:54) ~[micronaut-core-4.8.11.jar:4.8.11]
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete0(DelayedExecutionFlowImpl.java:75) ~[micronaut-core-4.8.11.jar:4.8.11]
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete(DelayedExecutionFlowImpl.java:82) ~[micronaut-core-4.8.11.jar:4.8.11]`

In fact is quite restrictive here:
[AbstractWatcher.onError()](https://github.com/micronaut-projects/micronaut-discovery-client/blob/4.7.x/discovery-client/src/main/java/io/micronaut/discovery/consul/watch/AbstractWatcher.java#L155)

### Steps To Reproduce
1. Ensure the configuration is set: `consul.client.watch.enabled = true`
2. Start the service
3. Check on the logs that the watcher is alive: `INFO 28128 --- [main] i.m.d.c.w.WatchTrigger:  Starting Consul watcher`
4. Update any Key in Consul KV
6. Stop Consul
7. Check the exceptions on the log: `HttpClientResponseException: rpc error making call: EOF`
8. Start Consul
9. Update any Key in Consul KV
10. Configuration not refreshed

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.9.3

### LINKED ISSUE #765: Consul Watch should log an Error on missing KV Path
### Expected Behavior

If Consul Watch cannot find a KV Path should log an ERROR / WARN instead of TRACE

### Actual Behaviour
Right now if you configure a Consul KV Path and its missing log is in TRACE, so the service starts, the watcher starts but it won't do anything and you miss it. Perhaps that log should be ERROR or at least WARN

[AbstractWatcher TRACE](https://github.com/micronaut-projects/micronaut-discovery-client/blob/4.7.x/discovery-client/src/main/java/io/micronaut/discovery/consul/watch/AbstractWatcher.java#L149)

### Version

4.9.3

### PR DESCRIPTION
**Pull request by FrogDevelopper**
- Add a retry mechanism when watcher got an unexpected exception (#764)
- Add a configuration to set log level for KV not found for watching (#765)

### CODE REVIEW

**Comment by FrogDevelopper** [comment]
@graemerocher

Task :test-suite-consul-graal-jacksondatabind:nativeTestCompile is failing

> Error: Substition: jdk.internal.misc.ScopedMemoryAccess.closeScope0(MemorySessionImpl) conflicts with previously registered: jdk.internal.misc.ScopedMemoryAccess.closeScope0(MemorySessionImpl)
> ...
>\* What went wrong:
Execution failed for task ':test-suite-consul-graal-jacksondatabind:nativeTestCompile'.
\> Process 'command '/opt/hostedtoolcache/graalvm-jdk-21_linux-x64_bin/21.0.0/x64/graalvm-jdk-21.0.9+7.1/bin/native-image'' finished with non-zero exit value 1

I'm able to run it (java 21 and java 25) locally, so I don't know why it is failing in Github action

**Comment by FrogDevelopper** [comment]
@graemerocher @sdelamo @alvarosanchez @jameskleeh 

Anyone know why the build failed in Github Action for GraalVM ?

**Comment by graemerocher** [comment]
@FrogDevelopper we will look into it

File: discovery-client/src/main/java/io/micronaut/discovery/consul/watch/WatchConfiguration.java [hunk 1]
```diff
@@ -53,4 +74,46 @@ public boolean isEnabled() {
     public void setEnabled(final boolean enabled) {
         this.enabled = enabled;
     }
+
+    /**
+     * @return Maximum number of retry attempts. Default to {@value DEFAULT_MAX_RETRIES}
```
Comment (alvarosanchez) [inline discovery-client/src/main/java/io/micronaut/discovery/consul/watch/WatchConfiguration.java:79]: Please add `@since 4.7.2` to these new properties.

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
Other than the `@since` tags, this is good to go
